[package]
name = "stock_trading_ml"
version = "0.1.0"
authors = ["Jason Phan"]
edition = "2021"
repository = "https://github.com/sudo-JP/Stock-Trading-ML.git"

[dependencies]
# for fork/exec, pipes, etc.
nix = { version = "0.27", features = ["process"] }
libc = "0.2"
anyhow = "1.0"

